services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "ollama serve > /dev/null 2>&1 & sleep 10 && ollama pull mistral:7b && tail -f /dev/null"

volumes:
  ollama_data:
